name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        ghc: [ '9.0.1', '9.2.1' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: latest
    - run: ghc word_by_word_montgomery.hs -o word_by_word_montgomery
